# Generated by Django 5.0.3 on 2024-03-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databarang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualan_items', to='databarang.barang')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='penjualan.penjualan')),
            ],
        ),
    ]
